version: "3"

services: 
  api:
    container_name: phones-api
    restart: always
    env_file: .env
    environment: 
      - MONGO_DB_STRING=$MONGO_DB_STRING
    build: .
    ports: 
      - "3000:3000"
    links:
      - database

  database: 
    container_name: mongodb
    image: mongo:5.0.3
    env_file: .env
    environment:
      - MONGO_DB_STRING=$MONGO_DB_STRING
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes: 
      - ./mongo_data:/data/db

    ports:
      - 3001:3001
    logging:
      driver: none 
